# Generated by Django 5.2.15 on 2026-06-25 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="fat_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="porcentaje masa grasa (%)",
            ),
        ),
        migrations.AddField(
            model_name="athleteprofile",
            name="lean_mass_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="porcentaje masa magra (%)",
            ),
        ),
        migrations.CreateModel(
            name="AthleteProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="fecha"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="peso (kg)"
                    ),
                ),
                (
                    "fat_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="porcentaje masa grasa (%)",
                    ),
                ),
                (
                    "lean_mass_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="porcentaje masa magra (%)",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="users.athleteprofile",
                        verbose_name="deportista",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de progreso",
                "verbose_name_plural": "registros de progreso",
                "ordering": ["-date"],
                "unique_together": {("athlete", "date")},
            },
        ),
    ]
