# Generated by Django 5.2.15 on 2026-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_athleteprofile_fat_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("principiante", "Principiante"),
                    ("intermedio", "Intermedio"),
                    ("avanzado", "Avanzado"),
                    ("elite", "Élite / Competición"),
                ],
                default="intermedio",
                max_length=50,
                verbose_name="nivel de experiencia",
            ),
        ),
        migrations.AddField(
            model_name="athleteprofile",
            name="sport",
            field=models.CharField(
                choices=[
                    ("mma", "MMA (Artes Marciales Mixtas)"),
                    ("karate", "Karate"),
                    ("bjj", "Jiu-Jitsu Brasileño (BJJ)"),
                    ("crossfit", "CrossFit"),
                    ("hyrox", "Hyrox"),
                    ("weight_loss", "Pérdida de Peso / Acondicionamiento"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=50,
                verbose_name="deporte principal",
            ),
        ),
        migrations.AddField(
            model_name="athleteprofile",
            name="training_goal",
            field=models.CharField(
                choices=[
                    ("fuerza_maxima", "Fuerza Máxima"),
                    ("potencia_explosiva", "Potencia Explosiva"),
                    ("resistencia_muscular", "Resistencia Muscular"),
                    ("hipertrofia", "Hipertrofia"),
                    ("perdida_grasa", "Pérdida de Grasa / Déficit"),
                    (
                        "acondicionamiento_combate",
                        "Capacidad Acondicionamiento de Combate",
                    ),
                ],
                default="potencia_explosiva",
                max_length=50,
                verbose_name="objetivo principal",
            ),
        ),
    ]
