# Generated by Django 5.1.4 on 2026-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuerza", "Fuerza"),
                            ("potencia", "Potencia"),
                            ("movilidad", "Movilidad"),
                            ("velocidad", "Velocidad"),
                            ("pliometria", "Pliometría"),
                            ("tecnica", "Técnica"),
                            ("tactica", "Táctica"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=50,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="enlace de video"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ejercicio",
                "verbose_name_plural": "ejercicios",
            },
        ),
        migrations.CreateModel(
            name="LoggedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_sets",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="series reales"
                    ),
                ),
                (
                    "actual_reps",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="repeticiones reales"
                    ),
                ),
                (
                    "actual_load",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="carga real"
                    ),
                ),
                (
                    "actual_rpe",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="RPE real"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
            ],
            options={
                "verbose_name": "ejercicio registrado",
                "verbose_name_plural": "ejercicios registrados",
            },
        ),
        migrations.CreateModel(
            name="PlannedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "sets",
                    models.CharField(blank=True, max_length=50, verbose_name="series"),
                ),
                (
                    "reps",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="repeticiones"
                    ),
                ),
                (
                    "load",
                    models.CharField(blank=True, max_length=50, verbose_name="carga"),
                ),
                (
                    "rpe",
                    models.CharField(blank=True, max_length=50, verbose_name="RPE"),
                ),
                (
                    "rir",
                    models.CharField(blank=True, max_length=50, verbose_name="RIR"),
                ),
                (
                    "tempo",
                    models.CharField(blank=True, max_length=50, verbose_name="tempo"),
                ),
                (
                    "focus",
                    models.CharField(blank=True, max_length=100, verbose_name="foco"),
                ),
                (
                    "rest",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="descanso"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="indicaciones")),
            ],
            options={
                "verbose_name": "ejercicio planificado",
                "verbose_name_plural": "ejercicios planificados",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nombre del plan"
                    ),
                ),
                ("target_date", models.DateField(verbose_name="fecha programada")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="completado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plan de entrenamiento",
                "verbose_name_plural": "planes de entrenamiento",
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha completado"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duración (minutos)"
                    ),
                ),
                (
                    "calories_burned",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="calorías consumidas"
                    ),
                ),
                (
                    "avg_heart_rate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="frecuencia cardíaca media"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="notas del deportista"),
                ),
            ],
            options={
                "verbose_name": "sesión de entrenamiento",
                "verbose_name_plural": "sesiones de entrenamiento",
            },
        ),
    ]
