# Generated by Django 5.1.4 on 2026-04-18 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_exercises",
                to="users.trainerprofile",
                verbose_name="creado por",
            ),
        ),
        migrations.AddField(
            model_name="plannedexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_in",
                to="training.exercise",
                verbose_name="ejercicio",
            ),
        ),
        migrations.AddField(
            model_name="loggedexercise",
            name="planned_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="training.plannedexercise",
                verbose_name="ejercicio planificado",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_plans",
                to="users.athleteprofile",
                verbose_name="deportista",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_plans",
                to="users.trainerprofile",
                verbose_name="entrenador",
            ),
        ),
        migrations.AddField(
            model_name="plannedexercise",
            name="workout_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_exercises",
                to="training.workoutplan",
                verbose_name="plan de entrenamiento",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="users.athleteprofile",
                verbose_name="deportista",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="workout_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="training.workoutplan",
                verbose_name="plan de entrenamiento",
            ),
        ),
        migrations.AddField(
            model_name="loggedexercise",
            name="workout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logged_exercises",
                to="training.workoutsession",
                verbose_name="sesión de entrenamiento",
            ),
        ),
    ]
