# Generated by Django 5.2.15 on 2026-07-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="enlace de video"
            ),
        ),
    ]
