# Generated by Django 5.2.15 on 2026-07-23 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_alter_exercise_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="movement_pattern",
            field=models.CharField(
                choices=[
                    ("empuje_horizontal", "Empuje Horizontal (Banca, Flexiones)"),
                    ("empuje_vertical", "Empuje Vertical (Press Militar)"),
                    ("traccion_horizontal", "Tracción Horizontal (Remo)"),
                    ("traccion_vertical", "Tracción Vertical (Dominadas)"),
                    (
                        "dominante_cadera",
                        "Dominante de Cadera (Peso Muerto, Hip Thrust)",
                    ),
                    (
                        "dominante_rodilla",
                        "Dominante de Rodilla (Sentadilla, Zancadas)",
                    ),
                    ("potencia_olimpica", "Potencia Olímpica (Snatch, Clean, Jerk)"),
                    ("metabolico", "Condición Metabólica (Sled, Carrera, Ergómetro)"),
                    ("isometria_agarre", "Agarre / Tracción Específica (BJJ/MMA Grip)"),
                    ("core_rotacional", "Core / Anti-Rotación (Landmine, Paloff)"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=50,
                verbose_name="patrón de movimiento",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="sport_tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="etiquetas de deportes"
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="sport",
            field=models.CharField(
                choices=[
                    ("mma", "MMA (Artes Marciales Mixtas)"),
                    ("karate", "Karate"),
                    ("bjj", "Jiu-Jitsu Brasileño (BJJ)"),
                    ("crossfit", "CrossFit"),
                    ("hyrox", "Hyrox"),
                    ("weight_loss", "Pérdida de Peso / Acondicionamiento"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=50,
                verbose_name="deporte en enfoque",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="session_rpe",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="RPE global de la sesión (1-10)",
            ),
        ),
        migrations.CreateModel(
            name="LoggedSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="número de serie"
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        default=0, verbose_name="repeticiones reales"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="peso real (kg)",
                    ),
                ),
                (
                    "rpe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="RPE",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="hora completada"
                    ),
                ),
                (
                    "logged_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="training.loggedexercise",
                        verbose_name="ejercicio registrado",
                    ),
                ),
            ],
            options={
                "verbose_name": "serie registrada",
                "verbose_name_plural": "series registradas",
                "ordering": ["set_number"],
            },
        ),
    ]
