# Generated by Django 6.0.7 on 2026-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_exercise_movement_pattern_exercise_sport_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedexercise",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="hora de finalización"
            ),
        ),
        migrations.AddField(
            model_name="loggedexercise",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="hora de inicio"
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="hora de inicio"
            ),
        ),
    ]
