# Generated by Django 6.0.7 on 2026-08-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_loggedexercise_finished_at_loggedexercise_started_at_and_more"),
        ("users", "0003_athleteprofile_experience_level_athleteprofile_sport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_exercises",
                to="users.trainerprofile",
                verbose_name="creado por",
            ),
        ),
        migrations.CreateModel(
            name="DisciplineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("mma", "MMA (Artes Marciales Mixtas)"),
                            ("karate", "Karate"),
                            ("bjj", "Jiu-Jitsu Brasileño (BJJ)"),
                            ("crossfit", "CrossFit"),
                            ("hyrox", "Hyrox"),
                            ("weight_loss", "Pérdida de Peso / Acondicionamiento"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="deporte",
                    ),
                ),
                (
                    "focus",
                    models.CharField(blank=True, max_length=200, verbose_name="foco"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="plantilla del sistema"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_templates",
                        to="users.trainerprofile",
                        verbose_name="creada por",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copies",
                        to="training.disciplinetemplate",
                        verbose_name="plantilla origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "plantilla por disciplina",
                "verbose_name_plural": "plantillas por disciplina",
                "ordering": ["sport", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "sets",
                    models.CharField(blank=True, max_length=50, verbose_name="series"),
                ),
                (
                    "reps",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="repeticiones"
                    ),
                ),
                (
                    "load",
                    models.CharField(blank=True, max_length=50, verbose_name="carga"),
                ),
                (
                    "rpe",
                    models.CharField(blank=True, max_length=50, verbose_name="RPE"),
                ),
                (
                    "rest",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="descanso"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="indicaciones")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_slots",
                        to="training.exercise",
                        verbose_name="ejercicio",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="training.disciplinetemplate",
                        verbose_name="plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejercicio de plantilla",
                "verbose_name_plural": "ejercicios de plantilla",
                "ordering": ["template", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseDisciplineFit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("mma", "MMA (Artes Marciales Mixtas)"),
                            ("karate", "Karate"),
                            ("bjj", "Jiu-Jitsu Brasileño (BJJ)"),
                            ("crossfit", "CrossFit"),
                            ("hyrox", "Hyrox"),
                            ("weight_loss", "Pérdida de Peso / Acondicionamiento"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="deporte",
                    ),
                ),
                (
                    "fit",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Ajuste bajo"),
                            (2, "Ajuste medio-bajo"),
                            (3, "Ajuste medio"),
                            (4, "Ajuste alto"),
                            (5, "Ajuste máximo"),
                        ],
                        default=3,
                        verbose_name="ajuste (1-5)",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_fits",
                        to="training.exercise",
                        verbose_name="ejercicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "encaje ejercicio-deporte",
                "verbose_name_plural": "encajes ejercicio-deporte",
                "ordering": ["-fit", "exercise"],
                "unique_together": {("exercise", "sport")},
            },
        ),
    ]
